//! Every compression codec, decompressed out of a real container.
//!
//! # Why this file exists
//!
//! Codec coverage is the project's most uneven area. Snappy is verified
//! against 121 real chunks; zlib and LZ4 have **no container of either codec
//! anywhere** — not in the reference corpus, not obtainable — so without this
//! file they rest on hand-built vectors decompressed in isolation. A vector
//! test proves the
//! decompressor works on bytes someone chose. It does not prove the *container*
//! path works: that the IRI resolves to the right codec, that the bevy index
//! locates compressed chunks whose lengths differ from `chunkSize`, that the
//! stored-chunk shortcut fires correctly, and that the digests still match.
//!
//! These fixtures close that gap. Each is a genuine AFF4 container whose bevies
//! hold compressed bytes, generated by `utilities/create_test_aff4.py` and
//! verified leaves-to-root through the ordinary `verify` path.
//!
//! # What a passing test here does and does not establish
//!
//! It establishes that aff4tools reads a container written by an *independent
//! implementation* of each codec — Python's `zlib`, `python-snappy`, and `lz4`
//! — rather than round-tripping its own output. That is the property that
//! matters: a bug shared between a Rust compressor and the Rust decompressor
//! would cancel out, and this cannot.
//!
//! It does **not** establish behaviour on real evidence. The payload is lorem
//! ipsum, which compresses roughly 60:1; real disk images do not. See the
//! warning at the top of `docs/testing.md`.
//!
//! Skipped when Python 3 or a codec module is unavailable, rather than failing:
//! these are generated fixtures, not a dependency of the library.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::{Path, PathBuf};
use std::process::Command;

use aff4tools::verify::{Outcome, VerifyOptions, verify_container};
use aff4tools::{Container, ObjectRole};

/// Codecs aff4tools decompresses, and so must verify end to end.
const DECODED: [&str; 4] = ["stored", "snappy", "zlib", "lz4"];

/// Generate a container using `codec`, or `None` if it cannot be built.
///
/// A missing Python module is a skip, not a failure: `python-snappy` and `lz4`
/// are not build dependencies of this crate.
fn generate(dir: &Path, codec: &str) -> Option<PathBuf> {
    let script = Path::new(env!("CARGO_MANIFEST_DIR")).join("utilities/create_test_aff4.py");
    let out = dir.join(format!("{codec}.aff4"));

    let result = Command::new("python3")
        .arg(&script)
        .arg("--codec")
        .arg(codec)
        .arg("--bevies")
        .arg("4")
        .arg("--chunk-size")
        .arg("4096")
        .arg("--chunks-in-segment")
        .arg("2")
        .arg(&out)
        .output()
        .ok()?;

    if !result.status.success() {
        // A missing compression module is the expected reason; anything else
        // is worth seeing rather than swallowing.
        eprintln!(
            "skipping {codec}: generator failed: {}",
            String::from_utf8_lossy(&result.stderr)
        );
        return None;
    }
    Some(out)
}

/// Every implemented codec verifies from leaves to root.
#[test]
fn each_codec_verifies_a_real_container() {
    let temp = tempfile::tempdir().unwrap();

    for codec in DECODED {
        let Some(path) = generate(temp.path(), codec) else {
            continue;
        };

        let mut container = Container::open(&path).unwrap();
        let report =
            verify_container(&mut container, VerifyOptions { block_hashes: true }).unwrap();

        assert!(
            !report.has_mismatch(),
            "a {codec} container must verify clean: {:#?}",
            report
                .checks
                .iter()
                .filter(|c| c.outcome.is_mismatch())
                .collect::<Vec<_>>()
        );
        assert!(
            report.match_count() >= 8,
            "{codec}: only {} digests matched; the tree was not fully checked",
            report.match_count()
        );

        // Reaching the leaves means chunks were actually decompressed and
        // hashed — the composite digests alone would pass over a bevy the
        // decoder never touched.
        assert!(
            report.block_hashes_verified,
            "{codec}: per-chunk hashing must have run"
        );
        let per_block = report
            .checks
            .iter()
            .filter(|c| c.coverage == aff4tools::Coverage::Block)
            .count();
        assert_eq!(
            per_block, 2,
            "{codec}: one per-chunk check per block-hash algorithm"
        );
    }
}

/// The bevies really are compressed, so the codec path is exercised.
///
/// The load-bearing assertion of this file. Without it every test here would
/// still pass if the generator silently wrote plaintext: the digests cover the
/// plaintext either way, and a stored chunk decodes trivially. Chunk length is
/// what distinguishes "decompressed correctly" from "never compressed".
#[test]
fn compressed_containers_hold_compressed_chunks() {
    let temp = tempfile::tempdir().unwrap();

    for codec in DECODED {
        let Some(path) = generate(temp.path(), codec) else {
            continue;
        };

        let mut container = Container::open(&path).unwrap();
        let summary = container.summarize().unwrap();
        let stream = summary
            .objects
            .iter()
            .find(|o| o.role == ObjectRole::ImageStream)
            .expect("the fixture declares an image stream");
        let declared = stream.size.expect("the stream declares a size");

        // Measured from the file itself rather than through the library, so a
        // bug in the library's own accounting cannot make this pass.
        let bevy_bytes = total_bevy_bytes(&path);

        if codec == "stored" {
            assert!(
                bevy_bytes >= declared / 2,
                "stored: bevies should be roughly the stream size, got \
                 {bevy_bytes} for {declared}"
            );
        } else {
            assert!(
                bevy_bytes < declared / 2,
                "{codec}: bevies hold {bevy_bytes} bytes for a {declared}-byte \
                 stream — the chunks were not compressed, so this codec was \
                 never exercised"
            );
        }
    }
}

/// Total uncompressed size of every bevy member, read straight from the ZIP.
///
/// Bevies are the numbered members with no extension; `.index` and
/// `.blockHash.*` siblings share the prefix and must not count.
fn total_bevy_bytes(path: &Path) -> u64 {
    let file = std::fs::File::open(path).unwrap();
    let mut archive = zip::ZipArchive::new(file).unwrap();
    let names: Vec<String> = archive.file_names().map(str::to_owned).collect();

    names
        .iter()
        .filter(|name| {
            name.rsplit_once('/').is_some_and(|(_, leaf)| {
                leaf.len() == 8 && leaf.bytes().all(|b| b.is_ascii_digit())
            })
        })
        .map(|name| archive.by_name(name).unwrap().size())
        .sum()
}

/// Raw deflate is recognised, declined, and never guessed at.
///
/// AFF4 gives deflate (RFC 1951) and zlib (RFC 1950) separate IRIs because they
/// are different byte streams, and this build decodes only zlib. The container
/// must therefore parse fully, report the codec by name, and recompute nothing
/// that depends on reading a chunk — rather than failing to open, or worse,
/// decoding it as zlib and producing a mismatch.
#[test]
fn raw_deflate_declines_with_its_reason() {
    let temp = tempfile::tempdir().unwrap();
    let Some(path) = generate(temp.path(), "deflate") else {
        return;
    };

    let mut container = Container::open(&path).unwrap();
    let report = verify_container(&mut container, VerifyOptions { block_hashes: true }).unwrap();

    // Not a mismatch: nothing was recomputed and found wrong.
    assert!(
        !report.has_mismatch(),
        "an unsupported codec is a limitation of this build, never a finding \
         about the evidence: {:#?}",
        report
            .checks
            .iter()
            .filter(|c| c.outcome.is_mismatch())
            .collect::<Vec<_>>()
    );

    let declined: Vec<&str> = report
        .checks
        .iter()
        .filter_map(|c| match &c.outcome {
            Outcome::NotVerifiable { reason, .. } => Some(reason.as_str()),
            _ => None,
        })
        .collect();

    assert!(
        declined.iter().any(|r| r.contains("rfc1951")),
        "the decline must name the codec that was not decoded: {declined:#?}"
    );

    // The structural digests still verify: metadata and map segments need no
    // chunk decoding, so a declined codec must not suppress them.
    assert!(
        report.match_count() >= 4,
        "the parts that need no decompression must still be checked, got {}",
        report.match_count()
    );
}

/// A codec fixture read through the parallel path gives identical digests.
///
/// Compressed chunks vary in length, so the bevy index — not a fixed stride —
/// is what locates them. The parallel reader decodes bevies off-thread, and an
/// index misread there would surface as a wrong digest rather than an error.
#[test]
fn codec_containers_agree_between_serial_and_parallel_reads() {
    let temp = tempfile::tempdir().unwrap();

    for codec in DECODED {
        let Some(path) = generate(temp.path(), codec) else {
            continue;
        };

        let digests = |threads: &str| {
            // SAFETY-free: the variable is read once at plan time, and the
            // tests in this file run in the same process sequentially.
            unsafe { std::env::set_var("AFF4TOOLS_THREADS", threads) };
            let mut container = Container::open(&path).unwrap();
            let report =
                verify_container(&mut container, VerifyOptions { block_hashes: true }).unwrap();
            report
                .checks
                .iter()
                .map(|c| {
                    (
                        c.subject.as_str().to_owned(),
                        c.predicate.clone(),
                        c.actual.clone(),
                    )
                })
                .collect::<Vec<_>>()
        };

        let serial = digests("1");
        let parallel = digests("4");
        unsafe { std::env::remove_var("AFF4TOOLS_THREADS") };

        assert_eq!(
            serial, parallel,
            "{codec}: serial and parallel reads disagree about the digests"
        );
    }
}
