//! Verification and reporting of a **discontiguous** image.
//!
//! No container in the canonical reference corpus is discontiguous.
//! But at least one commercial tool writes sparse acquisitions this way,
//! leaving regions uncovered and omitting `aff4:mapGapDefaultStream`
//! so the standard's `aff4:Zero` default applies.
//!
//! These fixtures are generated by `utilities/create_test_aff4.py
//! --discontiguous`. Skipped when Python 3 is unavailable, rather than failing:
//! this is a fixture generator, not a dependency of the library.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::{Path, PathBuf};
use std::process::Command;

use assert_cmd::Command as AssertCommand;

/// Build a discontiguous container, optionally declaring a gap stream.
///
/// Returns `None` when Python is not available.
fn generate(dir: &Path, gap_stream: Option<&str>) -> Option<PathBuf> {
    let script = Path::new(env!("CARGO_MANIFEST_DIR")).join("utilities/create_test_aff4.py");
    let out = dir.join("disc.aff4");

    let mut command = Command::new("python3");
    command
        .arg(&script)
        .arg("--bevies")
        .arg("4")
        .arg("--chunk-size")
        .arg("512")
        .arg("--discontiguous");
    if let Some(stream) = gap_stream {
        command.arg("--gap-stream").arg(stream);
    }
    let output = command.arg(&out).output().ok()?;

    assert!(
        output.status.success(),
        "generator failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    Some(out)
}

fn verify_text(container: &Path) -> String {
    let output = AssertCommand::cargo_bin("aff4tools")
        .expect("the binary must build")
        .arg("verify")
        .arg(container)
        .assert()
        .success()
        .get_output()
        .stdout
        .clone();
    String::from_utf8(output).expect("output must be UTF-8")
}

/// A container that declares no gap stream must not be reported as if it had.
///
/// v1.0a §4's `aff4:Zero` applies by default, but the container said nothing.
/// Naming `aff4:Zero` alone would attribute to it a claim it never made — the
/// failure mode CLAUDE.md's "don't invent format details" names. So the default
/// is named *and* flagged as inferred.
#[test]
fn an_undeclared_gap_stream_is_reported_as_the_spec_default() {
    let dir = tempfile::tempdir().unwrap();
    let Some(container) = generate(dir.path(), None) else {
        eprintln!("skipping: python3 not available");
        return;
    };

    let text = verify_text(&container);
    let qualified = "aff4:Zero (the §4 default; this container declares no mapGapDefaultStream)";
    // Asserted in *both* places. The accounting line and the note are rendered
    // through separate call sites, and an earlier revision had them disagree —
    // the accounting said "aff4:Zero" while the note qualified it.
    assert_eq!(
        text.matches(qualified).count(),
        2,
        "both the accounting line and the note must flag the default as \
         inferred, and word it identically:\n{text}"
    );
}

/// A container that *does* declare one is named plainly, with no disclaimer.
#[test]
fn a_declared_gap_stream_is_named_without_qualification() {
    let dir = tempfile::tempdir().unwrap();
    let Some(container) = generate(dir.path(), Some("aff4:FF")) else {
        eprintln!("skipping: python3 not available");
        return;
    };

    let text = verify_text(&container);
    assert!(
        text.contains("filled with aff4:FF"),
        "a declared gap stream must be named:\n{text}"
    );
    assert!(
        !text.contains("§4 default"),
        "a declared gap stream must carry no 'inferred' disclaimer:\n{text}"
    );
}

/// The note must say what the recorded digests do **not** cover.
///
/// This is the finding an examiner needs and the reason the note exists: half
/// this image's address space was never acquired, the container records no
/// whole-image digest, and a clean `verify` says nothing about those bytes
/// unless the report says so.
#[test]
fn the_note_states_that_no_digest_covers_the_filled_bytes() {
    let dir = tempfile::tempdir().unwrap();
    let Some(container) = generate(dir.path(), None) else {
        eprintln!("skipping: python3 not available");
        return;
    };

    let text = verify_text(&container);
    assert!(
        text.contains("This is a discontiguous image."),
        "the note must open by naming the shape:\n{text}"
    );
    assert!(
        text.contains("These bytes were not acquired."),
        "the note must say the bytes were never acquired:\n{text}"
    );
    assert!(
        text.contains("No digest recorded in this container covers them"),
        "the note must state the coverage gap:\n{text}"
    );
}

/// The accounting block names its source, and holes are never called content.
///
/// `map` rather than `read` says these figures came from the map's entries
/// without producing a byte. The earlier label was `content`, which invited
/// reading a hole's size as content that had been examined.
#[test]
fn the_accounting_names_the_map_as_its_source() {
    let dir = tempfile::tempdir().unwrap();
    let Some(container) = generate(dir.path(), None) else {
        eprintln!("skipping: python3 not available");
        return;
    };

    let text = verify_text(&container);
    assert!(
        text.contains("    map     "),
        "map-derived figures must be labelled `map`:\n{text}"
    );
    assert!(
        text.contains("holes from data not acquired"),
        "holes must be named as unacquired, not as content:\n{text}"
    );
    // The line this replaced. Its return would mean the wording regressed.
    assert!(
        !text.contains("the image was not read in full"),
        "the superseded disclaimer must not reappear:\n{text}"
    );
}

/// `verify` opens with the same identity block `info` does.
#[test]
fn verify_opens_with_the_containers_identity() {
    let dir = tempfile::tempdir().unwrap();
    let Some(container) = generate(dir.path(), None) else {
        eprintln!("skipping: python3 not available");
        return;
    };

    let text = verify_text(&container);
    let head: Vec<&str> = text.lines().take(6).collect();
    assert!(head[0].starts_with("Container:"), "got {head:?}");
    assert!(head[1].starts_with("Volume ARN:"), "got {head:?}");
    assert!(head[3].starts_with("Content Type:"), "got {head:?}");
    assert!(head[4].starts_with("AFF4 Version:"), "got {head:?}");
    assert!(head[5].starts_with("Tool:"), "got {head:?}");

    // No duplicate `Container:` line after the estimate.
    assert_eq!(
        text.matches("Container:").count(),
        1,
        "the container must be named exactly once:\n{text}"
    );
    // `Verified:` belongs with the checks it summarizes, not above the
    // accounting that says what was verified.
    let verified = text.find("Verification results:").expect("a verdict line");
    let accounting = text.find("    map     ").expect("an accounting block");
    assert!(
        accounting < verified,
        "the accounting must precede the verdict:\n{text}"
    );
}

/// The identity block reaches stdout before verification reads anything.
///
/// On a 256 GiB container the digest pass is minutes; which container is being
/// read is knowable the moment the metadata is parsed. Printing the header with
/// the rest of the report made a user wait for the whole run to learn what the
/// run was even about.
///
/// Asserted by timing rather than by content, because content alone cannot tell
/// "printed early" from "printed at the end in the right order". The gap is
/// generous — the point is that the header does not wait for the digests.
#[test]
fn the_identity_block_is_printed_before_reading_begins() {
    use std::io::{BufRead, BufReader};
    use std::process::Stdio;
    use std::time::Instant;

    let dir = tempfile::tempdir().unwrap();
    let script = Path::new(env!("CARGO_MANIFEST_DIR")).join("utilities/create_test_aff4.py");
    let container = dir.path().join("slow.aff4");

    // Large enough that hashing is measurably slower than parsing: zlib across
    // several thousand bevies, rather than the four the other tests use.
    let generated = Command::new("python3")
        .arg(&script)
        .arg("--bevies")
        .arg("8000")
        .arg("--chunk-size")
        .arg("512")
        .arg("--codec")
        .arg("zlib")
        .arg(&container)
        .output();
    let Ok(output) = generated else {
        eprintln!("skipping: python3 not available");
        return;
    };
    if !output.status.success() {
        eprintln!("skipping: generator failed");
        return;
    }

    let mut child = std::process::Command::new(env!("CARGO_BIN_EXE_aff4tools"))
        .arg("verify")
        .arg(&container)
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .expect("the binary must run");

    let started = Instant::now();
    let stdout = child.stdout.take().expect("piped stdout");
    let mut lines = BufReader::new(stdout).lines();

    let first = lines
        .next()
        .expect("output must not be empty")
        .expect("stdout must be readable");
    let header_at = started.elapsed();
    assert!(
        first.starts_with("Container:"),
        "the first line must identify the container, got {first:?}"
    );

    // Drain the rest, which cannot finish until the digests do.
    let mut last = String::new();
    for line in lines {
        last = line.expect("stdout must be readable");
    }
    let finished = started.elapsed();
    child.wait().expect("the process must exit");

    assert!(!last.is_empty(), "the report must continue past the header");
    assert!(
        header_at * 2 < finished,
        "the header must arrive well before the run ends; header at {header_at:?}, \
         finished at {finished:?}"
    );
}
