//! AFF4-L v1.0-ALPHA §4.4's digest algorithms, plus BLAKE3.
//!
//! # Where the expected values come from
//!
//! Not from this crate, and not from any specification. The five FIPS 202
//! values are generated by Python's `hashlib`, a different implementation from
//! the Rust crates under test, so a bug in one cannot be cancelled out by the
//! same bug in the fixture. The BLAKE3 value is the published test vector for
//! the empty input, taken from the reference repository's `test_vectors.json`.
//!
//! This mirrors the project's existing use of pyaff4 as an independent digest
//! oracle.

// Integration tests build fixture trees in temp dirs, which needs the
// directory constructors the library is denied. `tests/read_only_guard.rs`
// scans `src/` only, so this relaxation cannot reach library code.
#![allow(clippy::disallowed_methods)]

use aff4tools::{HashAlgorithm, hash, hash_selection};

const EMPTY_SHA3_256: &str = "a7ffc6f8bf1ed76651c14756a061d662f580ff4de43b49fa82d80a4b80f8434a";
const EMPTY_SHA3_384: &str = "0c63a75b845e4f7d01107d852e4c2485c51a50aaaa94fc61995e71bbee983a2ac3713831264adb47fb6bd1e058d5f004";
const EMPTY_SHA3_512: &str = "a69f73cca23a9ac5c8b567dc185a756e97c982164fe25859e0d1dcc1475c80a615b2123af1f5f94c11e3e9402c3ac558f500199d95b6d3e301758586281dcd26";
const EMPTY_SHAKE128: &str = "7f9c2ba4e88f827d616045507605853ed73b8093f6efbc88eb1a6eacfa66ef26";
const EMPTY_SHAKE256: &str = "46b9dd2b0ba88d13233b3feb743eeb243fcd52ea62b81b82b50c27646ed5762fd75dc4ddd8c0f200cb05019d67b592f6fc821c49479ab48640292eacb3b7c4be";
const EMPTY_BLAKE3: &str = "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262";

/// The empty input, whose digest is fixed by FIPS 202 for each function.
#[test]
fn the_new_algorithms_digest_the_empty_input() {
    for (algorithm, expected) in [
        (HashAlgorithm::Sha3_256, EMPTY_SHA3_256),
        (HashAlgorithm::Sha3_384, EMPTY_SHA3_384),
        (HashAlgorithm::Sha3_512, EMPTY_SHA3_512),
        (HashAlgorithm::Shake128, EMPTY_SHAKE128),
        (HashAlgorithm::Shake256, EMPTY_SHAKE256),
        (HashAlgorithm::Blake3, EMPTY_BLAKE3),
    ] {
        let got = hash::digest_of(&algorithm, b"").expect("computable");
        assert_eq!(got.hex(), expected, "{}", algorithm.name());
        assert_eq!(
            got.hex().len(),
            algorithm.hex_length().expect("a known length"),
            "{} digest length disagrees with hex_length",
            algorithm.name()
        );
    }
}

/// Every new algorithm reports itself computable, so `verify` attempts it
/// rather than declining it as unsupported.
#[test]
fn the_new_algorithms_are_computable() {
    for algorithm in [
        HashAlgorithm::Sha3_256,
        HashAlgorithm::Sha3_384,
        HashAlgorithm::Sha3_512,
        HashAlgorithm::Shake128,
        HashAlgorithm::Shake256,
        HashAlgorithm::Blake3,
    ] {
        assert!(hash::is_computable(&algorithm), "{}", algorithm.name());
    }
}

/// A non-empty input, so a bug that returns a constant is caught.
#[test]
fn a_non_empty_input_digests_differently() {
    for algorithm in [
        HashAlgorithm::Sha3_256,
        HashAlgorithm::Sha3_384,
        HashAlgorithm::Sha3_512,
        HashAlgorithm::Shake128,
        HashAlgorithm::Shake256,
        HashAlgorithm::Blake3,
    ] {
        let empty = hash::digest_of(&algorithm, b"").expect("computable");
        let some = hash::digest_of(&algorithm, b"aff4").expect("computable");
        assert_ne!(empty.hex(), some.hex(), "{}", algorithm.name());
    }
}

/// A datatype IRI names an algorithm, and the local name round-trips through
/// `name()` so a container this tool writes reads back as the same algorithm.
///
/// The hyphen in `SHA3-256` is legal in a Turtle prefixed name's local part, so
/// `aff4:SHA3-256` is what the writer emits and what a parser resolves back to
/// this IRI.
#[test]
fn the_new_datatype_iris_round_trip() {
    for (iri, algorithm) in [
        ("http://aff4.org/Schema#SHA3-256", HashAlgorithm::Sha3_256),
        ("http://aff4.org/Schema#SHA3-384", HashAlgorithm::Sha3_384),
        ("http://aff4.org/Schema#SHA3-512", HashAlgorithm::Sha3_512),
        ("http://aff4.org/Schema#SHAKE128", HashAlgorithm::Shake128),
        ("http://aff4.org/Schema#SHAKE256", HashAlgorithm::Shake256),
        ("http://aff4.org/Schema#BLAKE3", HashAlgorithm::Blake3),
    ] {
        assert_eq!(HashAlgorithm::from_datatype(iri), algorithm, "{iri}");
        assert_eq!(
            algorithm.name(),
            iri.rsplit('#').next().expect("a fragment"),
            "name() must reproduce the local part of {iri}"
        );
    }
}

/// A bare `SHA3` names no algorithm this build knows, and must not be mistaken
/// for one of the three sized variants.
#[test]
fn an_unsized_sha3_is_not_recognized() {
    assert_eq!(
        HashAlgorithm::from_datatype("http://aff4.org/Schema#SHA3"),
        HashAlgorithm::Other("SHA3".to_owned())
    );
}

/// The flag accepts repeated occurrences and comma-separated lists, in any
/// case, and rejects an unknown name rather than ignoring it.
#[test]
fn the_hash_flag_parses_every_accepted_form() {
    let one = hash_selection::parse(&["sha512".to_owned()]).expect("valid");
    assert_eq!(one, vec![HashAlgorithm::Sha512]);

    let comma = hash_selection::parse(&["sha512,blake3".to_owned()]).expect("valid");
    assert_eq!(comma, vec![HashAlgorithm::Sha512, HashAlgorithm::Blake3]);

    let repeated =
        hash_selection::parse(&["sha512".to_owned(), "blake3".to_owned()]).expect("valid");
    assert_eq!(repeated, comma);

    let mixed_case = hash_selection::parse(&["SHA3-256".to_owned()]).expect("valid");
    assert_eq!(mixed_case, vec![HashAlgorithm::Sha3_256]);

    // A repeat is collapsed, not recorded twice: two identical digests on one
    // object would be noise in the container.
    let duplicated = hash_selection::parse(&["sha512,sha512".to_owned()]).expect("valid");
    assert_eq!(duplicated, vec![HashAlgorithm::Sha512]);
}

/// An unknown name is refused, and the message names what is accepted. Silently
/// dropping it would record fewer digests than the examiner asked for.
#[test]
fn an_unknown_hash_name_is_refused() {
    let err = hash_selection::parse(&["sha4".to_owned()]).expect_err("refused");
    assert!(
        err.contains("sha4"),
        "the message names the bad input: {err}"
    );
    assert!(
        err.contains("sha512"),
        "the message lists what is valid: {err}"
    );
}

/// An empty selection is refused. Acquiring with no digest at all would
/// produce a container nothing can verify.
#[test]
fn an_empty_hash_selection_is_refused() {
    assert!(hash_selection::parse(&[",".to_owned()]).is_err());
    assert!(hash_selection::parse(&["".to_owned()]).is_err());
}

/// A selection of only broken algorithms is refused.
///
/// AFF4-L v1.0-ALPHA §10.1 requires the metadata integrity hash be SHA-256 or
/// stronger, and the same selection computes it, so this selection could only
/// produce a container that departs from the clause.
#[test]
fn a_weak_only_selection_is_refused() {
    for weak in ["md5", "sha1", "md5,sha1"] {
        let err = hash_selection::parse(&[weak.to_owned()])
            .expect_err("a weak-only selection is refused");
        assert!(
            err.contains("MD5") && err.contains("SHA-1"),
            "the message must name what is insufficient: {err}"
        );
    }
}

/// A weak algorithm is allowed alongside a qualifying one.
///
/// An examiner reproducing a legacy container's digests has a legitimate reason
/// to record MD5. What is refused is a selection with nothing stronger, not MD5
/// itself.
#[test]
fn a_weak_algorithm_is_allowed_beside_a_qualifying_one() {
    let chosen = hash_selection::parse(&["md5,sha256".to_owned()]).expect("valid");
    assert_eq!(
        chosen,
        vec![HashAlgorithm::Md5, HashAlgorithm::Sha256],
        "both are recorded, in the order given"
    );
}

/// Every algorithm at SHA-256 strength or above satisfies the clause, and the
/// two broken ones do not.
#[test]
fn the_integrity_clause_predicate_names_the_right_algorithms() {
    for qualifying in [
        HashAlgorithm::Sha256,
        HashAlgorithm::Sha512,
        HashAlgorithm::Blake2b,
        HashAlgorithm::Sha3_256,
        HashAlgorithm::Sha3_384,
        HashAlgorithm::Sha3_512,
        HashAlgorithm::Shake128,
        HashAlgorithm::Shake256,
        HashAlgorithm::Blake3,
    ] {
        assert!(
            hash_selection::satisfies_integrity_clause(&qualifying),
            "{}",
            qualifying.name()
        );
    }
    for weak in [HashAlgorithm::Md5, HashAlgorithm::Sha1] {
        assert!(
            !hash_selection::satisfies_integrity_clause(&weak),
            "{}",
            weak.name()
        );
    }
}

/// The documented defaults.
#[test]
fn the_defaults_are_sha512_and_blake3() {
    assert_eq!(
        hash_selection::DEFAULT.to_vec(),
        vec![HashAlgorithm::Sha512, HashAlgorithm::Blake3]
    );
}

/// `acquire` refuses a weak-only selection and writes nothing.
///
/// The absence of the output file is the assertion. A tool that refused after
/// creating the container would leave a partial artifact behind, and the
/// examiner might not notice which run produced it.
#[test]
fn acquire_refuses_a_weak_only_selection_without_writing() {
    let dir = tempfile::tempdir().expect("a temp dir");
    let source = dir.path().join("evidence");
    std::fs::create_dir_all(&source).expect("the tree");
    std::fs::write(source.join("a.txt"), b"content\n").expect("a file");

    let container = dir.path().join("out.aff4");
    let out = std::process::Command::new(env!("CARGO_BIN_EXE_aff4tools"))
        .args(["acquire", "--logical"])
        .arg(&source)
        .arg("--output")
        .arg(&container)
        .args(["--hash", "md5,sha1"])
        .output()
        .expect("aff4tools ran");

    assert!(
        !out.status.success(),
        "a weak-only selection must be refused"
    );

    let message = String::from_utf8_lossy(&out.stderr);
    assert!(
        message.contains("MD5") && message.contains("SHA-1"),
        "the message names what is insufficient: {message}"
    );
    assert!(
        !container.exists(),
        "no container may be written when the selection is refused"
    );
}

/// The selected algorithms are what the container records, and nothing else.
#[test]
fn the_selected_algorithms_are_what_gets_recorded() {
    let dir = tempfile::tempdir().expect("a temp dir");
    let source = dir.path().join("evidence");
    std::fs::create_dir_all(&source).expect("the source tree");
    std::fs::write(source.join("a.txt"), b"content\n").expect("a file");

    let container = dir.path().join("out.aff4");
    let status = std::process::Command::new(env!("CARGO_BIN_EXE_aff4tools"))
        .args(["acquire", "--logical"])
        .arg(&source)
        .arg("--output")
        .arg(&container)
        .args(["--hash", "sha256,sha3-512"])
        .status()
        .expect("aff4tools ran");
    assert!(status.success());

    let turtle = read_turtle(&container);
    assert!(turtle.contains("SHA256"), "sha256 was asked for:\n{turtle}");
    assert!(
        turtle.contains("SHA3-512"),
        "sha3-512 was asked for:\n{turtle}"
    );
    assert!(!turtle.contains("MD5"), "md5 was not asked for:\n{turtle}");
    assert!(
        !turtle.contains("^^aff4:SHA1"),
        "sha1 was not asked for:\n{turtle}"
    );
}

/// Without the flag, the defaults are recorded — and MD5 and SHA-1 are not.
#[test]
fn the_default_selection_replaces_md5_and_sha1() {
    let dir = tempfile::tempdir().expect("a temp dir");
    let source = dir.path().join("evidence");
    std::fs::create_dir_all(&source).expect("the source tree");
    std::fs::write(source.join("a.txt"), b"content\n").expect("a file");

    let container = dir.path().join("out.aff4");
    let status = std::process::Command::new(env!("CARGO_BIN_EXE_aff4tools"))
        .args(["acquire", "--logical"])
        .arg(&source)
        .arg("--output")
        .arg(&container)
        .status()
        .expect("aff4tools ran");
    assert!(status.success());

    let turtle = read_turtle(&container);
    assert!(turtle.contains("SHA512"), "a default:\n{turtle}");
    assert!(turtle.contains("BLAKE3"), "a default:\n{turtle}");
    assert!(!turtle.contains("MD5"), "MD5 is retired:\n{turtle}");
}

/// A datatype carrying a hyphen round-trips through a real container.
///
/// `aff4:SHA3-512` is legal Turtle, and this proves the written container
/// parses back to the datatype IRI it stands for rather than to something the
/// abbreviation rules mangled.
#[test]
fn a_hyphenated_datatype_survives_a_real_container() {
    let dir = tempfile::tempdir().expect("a temp dir");
    let source = dir.path().join("evidence");
    std::fs::create_dir_all(&source).expect("the source tree");
    std::fs::write(source.join("a.txt"), b"content\n").expect("a file");

    let container = dir.path().join("out.aff4");
    let status = std::process::Command::new(env!("CARGO_BIN_EXE_aff4tools"))
        .args(["acquire", "--logical"])
        .arg(&source)
        .arg("--output")
        .arg(&container)
        .args(["--hash", "sha3-256"])
        .status()
        .expect("aff4tools ran");
    assert!(status.success());

    let turtle = read_turtle(&container);
    let mut found = false;
    for triple in oxttl::TurtleParser::new().for_reader(turtle.as_bytes()) {
        let triple = triple.expect("the written metadata parses");
        if let oxrdf::Term::Literal(literal) = &triple.object
            && literal.datatype().as_str() == "http://aff4.org/Schema#SHA3-256"
        {
            found = true;
        }
    }
    assert!(
        found,
        "a SHA3-256 datatype must parse back to its IRI:\n{turtle}"
    );
}

/// Read `information.turtle` out of a written container.
fn read_turtle(container: &std::path::Path) -> String {
    let file = std::fs::File::open(container).expect("the container opens");
    let mut zip = zip::ZipArchive::new(file).expect("a zip");
    let mut entry = zip
        .by_name("information.turtle")
        .expect("the metadata segment");
    let mut body = String::new();
    std::io::Read::read_to_string(&mut entry, &mut body).expect("readable");
    body
}
