//! Striped containers beyond what the reference corpus can express.
//!
//! The corpus holds exactly **one** striped fixture: two volumes, one bevy per
//! stream. That cannot exercise `n > 2`, and — more importantly — it cannot
//! distinguish the candidate rules for **stripe order**.
//!
//! Stripe order matters because a striped image's root digest is
//! `SHA-512(blockMapHash₁ ‖ blockMapHash₂ ‖ …)`, which is order-sensitive. On
//! the two-volume fixture, sorting by filename and sorting by map ARN happen to
//! agree, so either rule looks correct. That agreement is a coincidence of two
//! samples, not evidence.
//!
//! These fixtures are generated by `utilities/create_test_aff4.py` with
//! deliberately **adversarial** orderings, so the candidate keys disagree:
//!
//! | `--arn-order` | filename | map ARN | stream ARN |
//! |---|---|---|---|
//! | `matching` | 1,2,3 | 1,2,3 | 1,2,3 |
//! | `reversed` | 1,2,3 | 3,2,1 | 3,2,1 |
//! | `shuffled` | 1,2,3 | 1,2,3 | 3,2,1 |
//!
//! In every case the *generator* writes the root in filename order, so a rule
//! that sorts by an ARN gets `reversed` and `shuffled` wrong. That is the
//! discrimination the corpus cannot provide.
//!
//! Skipped when Python 3 is unavailable, rather than failing: this is a fixture
//! generator, not a dependency of the library.

// Integration tests build fixture trees in temp dirs, which needs the
// directory constructors the library is denied. `tests/read_only_guard.rs`
// scans `src/` only, so this relaxation cannot reach library code.
#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
#![allow(clippy::disallowed_methods)]

use std::path::{Path, PathBuf};
use std::process::Command;

use aff4tools::verify::{VerifyOptions, verify_container};
use aff4tools::zip_volume_set::{VolumeOrigin, open_with_graph};
use aff4tools::{Container, ObjectRole, Outcome};

/// Generate a striped set, returning its volume paths in filename order.
///
/// Returns `None` when Python is not available.
fn generate(dir: &Path, stripes: usize, arn_order: &str, defect: &str) -> Option<Vec<PathBuf>> {
    let script = Path::new(env!("CARGO_MANIFEST_DIR")).join("utilities/create_test_aff4.py");
    let out = dir.join("gen.aff4");

    let status = Command::new("python3")
        .arg(&script)
        .arg("--stripes")
        .arg(stripes.to_string())
        .arg("--bevies")
        .arg("12")
        .arg("--chunk-size")
        .arg("512")
        .arg("--chunks-in-segment")
        .arg("1")
        .arg("--arn-order")
        .arg(arn_order)
        .arg("--stripe-defect")
        .arg(defect)
        .arg(&out)
        .output()
        .ok()?;

    assert!(
        status.status.success(),
        "generator failed: {}",
        String::from_utf8_lossy(&status.stderr)
    );

    Some(
        (1..=stripes)
            .map(|i| dir.join(format!("gen_{i}.aff4")))
            .collect(),
    )
}

/// Open a set with `paths[0]` primary and the rest joined in.
fn open_set(paths: &[PathBuf]) -> Container {
    let mut container = Container::open(&paths[0]).unwrap();
    for path in &paths[1..] {
        let (volume, graph) = open_with_graph(path).unwrap();
        container.add_volume(volume, graph, VolumeOrigin::Named);
    }
    container
}

/// Sets of 2, 3, and 5 stripes all verify clean.
///
/// The corpus has only the 2-volume case. Three and five catch anything that
/// works for a pair by accident — an ordering assumption, or a two-element
/// special case in the block-hash concatenation.
#[test]
fn generated_striped_sets_verify_at_several_widths() {
    let temp = tempfile::tempdir().unwrap();

    for stripes in [2usize, 3, 5] {
        let dir = temp.path().join(format!("w{stripes}"));
        std::fs::create_dir_all(&dir).unwrap();
        let Some(paths) = generate(&dir, stripes, "matching", "none") else {
            eprintln!("python3 unavailable; skipping");
            return;
        };

        let mut container = open_set(&paths);
        assert_eq!(container.volumes().len(), stripes);

        let report =
            verify_container(&mut container, VerifyOptions { block_hashes: true }).unwrap();

        assert!(
            !report.has_mismatch(),
            "{stripes}-stripe set must verify clean: {:#?}",
            report
                .checks
                .iter()
                .filter(|c| c.outcome.is_mismatch())
                .collect::<Vec<_>>()
        );

        // Every stripe carries its own map with its own `blockMapHash`, and
        // every one must be verified — against *that* stripe's segments. The
        // count growing with the width is what shows no stripe's digests are
        // being skipped because they are not the primary's.
        let block_map = report
            .checks
            .iter()
            .filter(|c| c.predicate == "blockMapHash")
            .count();
        assert_eq!(
            block_map,
            stripes,
            "every stripe's blockMapHash must be recomputed, not just the \
             primary's: {:#?}",
            report
                .checks
                .iter()
                .filter(|c| c.predicate == "blockMapHash")
                .collect::<Vec<_>>()
        );

        // Likewise each stripe's own stream digests.
        let stream_hashes = report
            .checks
            .iter()
            .filter(|c| c.role == ObjectRole::ImageStream && c.outcome == Outcome::Match)
            .count();
        assert!(
            stream_hashes >= stripes * 2,
            "each stripe records MD5 and SHA-256 over its own stream; got \
             {stream_hashes} matches across {stripes} stripes"
        );
    }
}

/// Every volume of a set holds a distinct part of the image.
///
/// Guards the property the whole feature rests on: `holding()` must route each
/// stream to the file that actually stores its bevies. If every stream resolved
/// to the primary, the set would still "verify" — against the wrong bytes.
#[test]
fn each_generated_stripe_holds_its_own_streams() {
    let temp = tempfile::tempdir().unwrap();
    let Some(paths) = generate(temp.path(), 3, "matching", "none") else {
        eprintln!("python3 unavailable; skipping");
        return;
    };

    let container = open_set(&paths);
    let summary = Container::open(&paths[0]).unwrap().summarize().unwrap();

    let streams: Vec<_> = summary
        .objects
        .iter()
        .filter(|o| o.role == ObjectRole::ImageStream)
        .collect();
    assert_eq!(streams.len(), 3, "every volume declares all three streams");

    let mut holders: Vec<String> = streams
        .iter()
        .filter_map(|s| container.volumes().holding(&s.arn))
        .map(|a| a.as_str().to_owned())
        .collect();
    holders.sort();
    holders.dedup();

    assert_eq!(
        holders.len(),
        3,
        "each stream's data must live in a different volume, not all in the primary"
    );
}

/// Adversarial ARN orderings still verify, and still disagree about order.
///
/// Each set is internally consistent — every per-stripe digest matches — while
/// the candidate ordering keys point different ways. A future Stage 6 must pick
/// filename order here and be *seen* to; these fixtures are what make that
/// checkable rather than assumed.
#[test]
fn adversarial_arn_orderings_verify_and_disagree() {
    let temp = tempfile::tempdir().unwrap();

    for order in ["matching", "reversed", "shuffled"] {
        let dir = temp.path().join(order);
        std::fs::create_dir_all(&dir).unwrap();
        let Some(paths) = generate(&dir, 3, order, "none") else {
            eprintln!("python3 unavailable; skipping");
            return;
        };

        let mut container = open_set(&paths);
        let report =
            verify_container(&mut container, VerifyOptions { block_hashes: true }).unwrap();

        assert!(
            !report.has_mismatch(),
            "the {order} set must verify clean — an adversarial ARN order is \
             not a defect, only an inconvenient one: {:#?}",
            report
                .checks
                .iter()
                .filter(|c| c.outcome.is_mismatch())
                .collect::<Vec<_>>()
        );

        // Volume ARNs sort against filename order for two of the three sets.
        // Assert the fixture really is adversarial, so a change to the
        // generator cannot quietly make these tests vacuous.
        let arns: Vec<&str> = container
            .volumes()
            .volume_arns()
            .map(aff4tools::Arn::as_str)
            .collect();
        let mut sorted = arns.clone();
        sorted.sort_unstable();
        if order == "matching" {
            assert_eq!(arns, sorted, "matching: ARN order follows filename order");
        } else {
            assert_ne!(
                arns, sorted,
                "{order}: volume-ARN order must disagree with filename order, \
                 or this fixture proves nothing"
            );
        }
    }
}

/// `info` reports a cross-volume conflict instead of absorbing it.
///
/// These four tests guard against a gap where the detection logic exists in
/// the library and is wired into `verify`, but `summarize` never calls it — so
/// `info` renders a defective container as clean.
///
/// These tests share the library's parsing assumptions. They guard against
/// regression, not against a misreading: a green run here does not mean the
/// values were independently validated.
#[test]
fn info_reports_a_cross_volume_conflict() {
    let temp = tempfile::tempdir().unwrap();
    let Some(paths) = generate(temp.path(), 2, "matching", "conflicting-chunk-size") else {
        eprintln!("python3 unavailable; skipping");
        return;
    };

    let mut container = open_set(&paths);
    let summary = container.summarize().unwrap();

    let conflict = summary
        .deviations
        .iter()
        .find(|d| d.kind == aff4tools::DeviationKind::ConflictingStreamValue)
        .expect("the chunkSize disagreement must be reported as a deviation");

    // Both values and both volumes: "512 and 1024" alone would not tell an
    // examiner which file to open.
    let detail = &conflict.detail;
    assert!(detail.contains("512"), "{detail}");
    assert!(detail.contains("1024"), "{detail}");
    let locus = conflict.locus.to_string();
    assert!(locus.contains("chunkSize"), "{locus}");
}

/// A single stripe has no sibling to disagree with, and must not be faulted.
///
/// The conflict check only means anything with two volumes admitted. Opening
/// one stripe alone is ordinary, and a deviation here would fire on every
/// striped container an examiner inspects one file at a time.
#[test]
fn one_stripe_alone_reports_no_conflict() {
    let temp = tempfile::tempdir().unwrap();
    let Some(paths) = generate(temp.path(), 2, "matching", "conflicting-chunk-size") else {
        eprintln!("python3 unavailable; skipping");
        return;
    };

    let mut container = Container::open(&paths[0]).unwrap();
    let summary = container.summarize().unwrap();

    assert!(
        !summary
            .deviations
            .iter()
            .any(|d| d.kind == aff4tools::DeviationKind::ConflictingStreamValue),
        "one volume cannot conflict with itself: {:?}",
        summary.deviations
    );
}

/// An edge naming an ARN nothing describes is reported.
///
/// `missing-metadata` removes a stream's declaration while leaving the
/// `dependentStream` edge pointing at it. Before B0 this container reported no
/// deviations at all.
#[test]
fn info_reports_a_dangling_data_path_edge() {
    let temp = tempfile::tempdir().unwrap();
    let Some(paths) = generate(temp.path(), 2, "matching", "missing-metadata") else {
        eprintln!("python3 unavailable; skipping");
        return;
    };

    let mut container = Container::open(&paths[0]).unwrap();
    let summary = container.summarize().unwrap();

    let dangling = summary
        .deviations
        .iter()
        .find(|d| d.kind == aff4tools::DeviationKind::DanglingReference)
        .expect("the unresolvable dependentStream must be reported");

    assert!(
        dangling.detail.contains("dependentStream"),
        "the deviation must name the predicate that could not be followed: {}",
        dangling.detail
    );
}

/// Routine deviations exist and are excluded from the strict verdict.
///
/// A lone stripe legitimately carries an `ExternalReference`. Once that was the
/// only thing standing between exit 0 and exit 7, `--strict` carried no
/// information — it fired on well-formed containers while the real conflict
/// went unreported.
#[test]
fn a_lone_stripe_is_not_a_strict_failure() {
    let temp = tempfile::tempdir().unwrap();
    let Some(paths) = generate(temp.path(), 2, "matching", "none") else {
        eprintln!("python3 unavailable; skipping");
        return;
    };

    let mut container = Container::open(&paths[0]).unwrap();
    let summary = container.summarize().unwrap();

    assert!(
        summary
            .deviations
            .iter()
            .any(|d| d.kind == aff4tools::DeviationKind::ExternalReference),
        "a lone stripe must still report the external reference"
    );
    assert!(
        !summary.has_noteworthy_deviation(),
        "but it must not fail --strict: {:?}",
        summary.deviations
    );
}

/// Volumes disagreeing about one stream are declined, not reconciled.
///
/// Two volumes claiming different chunk sizes for the same stream cannot both
/// be right. Picking a side would produce a digest no one could attribute, so
/// the image must fail to resolve and say why.
#[test]
fn conflicting_stream_metadata_is_declined() {
    let temp = tempfile::tempdir().unwrap();
    let Some(paths) = generate(temp.path(), 2, "matching", "conflicting-chunk-size") else {
        eprintln!("python3 unavailable; skipping");
        return;
    };

    let mut container = open_set(&paths);
    let report = verify_container(&mut container, VerifyOptions { block_hashes: true }).unwrap();

    let declined = report
        .checks
        .iter()
        .find(|c| c.actual.is_empty() && c.coverage == aff4tools::Coverage::WholeImage)
        .expect("the image-level digest must be declined");

    let reason = format!("{:?}", declined.outcome);
    assert!(
        reason.contains("disagree"),
        "the decline must name the disagreement rather than picking a side: {reason}"
    );

    // A conflict is not a mismatch: nothing was recomputed and found wrong.
    assert!(
        !report.has_mismatch(),
        "an unreadable set must not be reported as failing verification"
    );
}

/// Joining volumes must never reduce what gets verified.
///
/// A volume of a set may declare an image of its own, which the primary has
/// never heard of. Resolving every image against the *primary's* graph then
/// failed with "names no data stream" on an image that names one perfectly
/// well — downgrading a digest that verifies when the same file is opened
/// alone, while the headline still read "N of N matched".
///
/// The guard: whatever a volume verifies by itself, it must still verify as
/// part of a set.
#[test]
fn joining_volumes_never_loses_a_check() {
    let temp = tempfile::tempdir().unwrap();
    let Some(paths) = generate(temp.path(), 3, "matching", "none") else {
        eprintln!("python3 unavailable; skipping");
        return;
    };

    // Compared by identity, not count: the volumes of a striped set share
    // objects, so summing per-file totals would triple-count them.
    let matched = |report: &aff4tools::VerificationReport| {
        report
            .checks
            .iter()
            .filter(|c| c.outcome == Outcome::Match)
            .map(|c| (c.subject.as_str().to_owned(), c.predicate.clone()))
            .collect::<std::collections::BTreeSet<_>>()
    };

    let mut alone = std::collections::BTreeSet::new();
    for path in &paths {
        let mut container = Container::open(path).unwrap();
        let report =
            verify_container(&mut container, VerifyOptions { block_hashes: true }).unwrap();
        alone.extend(matched(&report));
    }

    let mut container = open_set(&paths);
    let report = verify_container(&mut container, VerifyOptions { block_hashes: true }).unwrap();
    let joined = matched(&report);

    let lost: Vec<_> = alone.difference(&joined).collect();
    assert!(
        lost.is_empty(),
        "these digests verify when their volume is opened alone but not when \
         it is part of a set — joining lost coverage: {lost:#?}"
    );
}

/// A volume carrying an image of its own keeps it verifiable in a set.
///
/// The regression Fix 2 addressed: `Image::open_in_set` resolved every image
/// against the **primary's** graph. A volume that declares an image the primary
/// has never heard of then failed with "names no data stream" — a false
/// statement about an intact container, and a digest silently downgraded from
/// MATCH to a decline.
///
/// Built from a striped set plus a *generated single* container, which declares
/// an image of its own. They are not one striped set — that is the point: the
/// primary's graph cannot describe the second volume's image.
///
/// The single container is generated rather than taken from the corpus so this
/// test needs no `--features corpus`; the striped half comes from the generator
/// too, so the two ARN families cannot collide.
#[test]
fn an_image_declared_by_only_one_volume_still_verifies() {
    let temp = tempfile::tempdir().unwrap();

    let striped_dir = temp.path().join("striped");
    std::fs::create_dir_all(&striped_dir).unwrap();
    let Some(striped) = generate(&striped_dir, 2, "matching", "none") else {
        eprintln!("python3 unavailable; skipping");
        return;
    };

    let solo_dir = temp.path().join("solo");
    std::fs::create_dir_all(&solo_dir).unwrap();
    let script = Path::new(env!("CARGO_MANIFEST_DIR")).join("utilities/create_test_aff4.py");
    let solo_path = solo_dir.join("one.aff4");
    let result = Command::new("python3")
        .arg(&script)
        .arg("--bevies")
        .arg("4")
        .arg("--chunk-size")
        .arg("512")
        .arg("--chunks-in-segment")
        .arg("1")
        .arg(&solo_path)
        .output()
        .unwrap();
    assert!(result.status.success());

    // Primary is a stripe; the solo container joins as a second volume whose
    // image the primary has never declared.
    let paths = vec![striped[0].clone(), solo_path];

    // What the second file verifies on its own.
    let mut solo = Container::open(&paths[1]).unwrap();
    let solo_report = verify_container(&mut solo, VerifyOptions { block_hashes: true }).unwrap();
    let solo_matches: std::collections::BTreeSet<_> = solo_report
        .checks
        .iter()
        .filter(|c| c.outcome == Outcome::Match)
        .map(|c| (c.subject.as_str().to_owned(), c.predicate.clone()))
        .collect();
    assert!(!solo_matches.is_empty());

    // The same file as the *second* volume of a set, so the primary's graph
    // knows nothing of its image.
    let mut container = open_set(&paths);
    let report = verify_container(&mut container, VerifyOptions { block_hashes: true }).unwrap();
    let joined: std::collections::BTreeSet<_> = report
        .checks
        .iter()
        .filter(|c| c.outcome == Outcome::Match)
        .map(|c| (c.subject.as_str().to_owned(), c.predicate.clone()))
        .collect();

    let lost: Vec<_> = solo_matches.difference(&joined).collect();
    assert!(
        lost.is_empty(),
        "a second volume's own image must stay verifiable when it is not the \
         primary; these were lost: {lost:#?}"
    );
}
