#!/usr/bin/env python3
"""Create minimal AFF4-L Standard v1.0-ALPHA (v2.1) containers.

Purpose: Create small test .aff4l v2.1 containers without relying on
the aff4tools writer. Adjust this script as the 2026 spec evolves.

Written independently of the aff4tools writer, so a reader bug and a writer bug
cannot cancel out. Nothing here is copied from the specification: the UUIDs,
sizes, and content are generated by this script.

These are NOT accepted, canonical reference images and must not be presented as such.
They are test inputs for an AFF4-L reader that has no other v2.1 containers to read.
"""

import argparse
import hashlib
import struct
import zipfile
from pathlib import Path

VOLUME = "aff4://3f2b91c4-5d7e-4a18-9c60-2e8b7f14a3d9"
FILE_IMAGE = "aff4://7c41e082-b3a9-4f56-8d21-6a0f9e5c7b34"

TURTLE_PREFIXES = """\
@prefix aff4:  <http://aff4.org/Schema#> .
@prefix aff4l: <http://aff4.org/Schema/2022/#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
"""


def _metadata_hashes(turtle_bytes: bytes) -> str:
    """The AFF4-L v1.0-ALPHA §10.1 companion segment for a metadata body.

    Computed here with hashlib, independently of the aff4tools writer, so a
    fixture cannot inherit a bug from the implementation it tests.
    """
    return TURTLE_PREFIXES + f"""
<{VOLUME}/information.turtle>
    aff4:hash "{hashlib.sha256(turtle_bytes).hexdigest()}"^^aff4:SHA256 .
"""


def write_minimal(path: Path) -> None:
    """A v2.1 container declaring only its volume."""
    turtle = TURTLE_PREFIXES + f"""
<{VOLUME}>
    a           aff4:ZipVolume ;
    aff4:stored "{path.name}" .
"""
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        # container.description first, per AFF4 Standard v1.0a §5.4.
        z.writestr("container.description", VOLUME)
        z.writestr("version.txt", "major=2\nminor=1\ntool=aff4tools-test 0.1\n")
        z.writestr("information.turtle", turtle)
        z.writestr("information.turtle.hashes", _metadata_hashes(turtle.encode()))
        z.comment = VOLUME.encode()


def write_conformant(path: Path) -> None:
    """A v2.1 container with one file stored as a ZIP segment."""
    content = b"This is test content.\n"
    sha1 = hashlib.sha1(content).hexdigest()
    md5 = hashlib.md5(content).hexdigest()

    turtle = TURTLE_PREFIXES + f"""
<{VOLUME}>
    a           aff4:ZipVolume ;
    aff4:stored "{path.name}" .

<{FILE_IMAGE}>
    a                       aff4:FileImage , aff4:Image , aff4:ZipSegment ;
    aff4:hash               "{sha1}"^^aff4:SHA1 , "{md5}"^^aff4:MD5 ;
    aff4:size               "{len(content)}"^^xsd:long ;
    aff4:fileName           "test.txt" ;
    aff4:originalPathName   "/test.txt" .
"""
    turtle_bytes = turtle.encode()
    hashes = _metadata_hashes(turtle_bytes)
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("container.description", VOLUME)
        z.writestr("version.txt", "major=2\nminor=1\ntool=aff4tools-test 0.1\n")
        # The stream's content lives under its own ARN as the member name,
        # per AFF4-L v1.0-ALPHA §6.1.
        z.writestr(FILE_IMAGE, content)
        z.writestr("information.turtle", turtle_bytes)
        z.writestr("information.turtle.hashes", hashes)
        z.comment = VOLUME.encode()


def _file_subject(arn: str, name: str, path: str, content: bytes) -> str:
    """One FileImage subject, stored as a ZIP segment."""
    return f"""
<{arn}>
    a                       aff4:FileImage , aff4:Image , aff4:ZipSegment ;
    aff4:hash               "{hashlib.sha1(content).hexdigest()}"^^aff4:SHA1 ;
    aff4:size               "{len(content)}"^^xsd:long ;
    aff4:fileName           "{name}" ;
    aff4:originalPathName   "{path}" .
"""


def _write(path: Path, turtle: str, members: dict) -> None:
    """Assemble a v2.1 container from a turtle body and its stored members."""
    body = TURTLE_PREFIXES + turtle
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("container.description", VOLUME)
        z.writestr("version.txt", "major=2\nminor=1\ntool=aff4tools-test 0.1\n")
        for name, content in members.items():
            z.writestr(name, content)
        z.writestr("information.turtle", body)
        z.writestr("information.turtle.hashes", _metadata_hashes(body.encode()))
        z.comment = VOLUME.encode()


def _map_digests(entry: bytes, idx: bytes, mappath: bytes = b"") -> str:
    """The four AFF4 Standard v1.0a section 6.2 digests over a map's segments.

    mapPointHash covers the map segment, mapIdxHash the idx segment,
    mapPathHash the mapPath segment, and mapHash the three concatenated in
    that order. The construction is confirmed against Base-Linear.aff4, whose
    recorded values it reproduces exactly.

    A conforming fixture must carry these: without them aff4tools reports the
    map as missing its integrity digests, which is a true finding about the
    fixture rather than a false positive.
    """
    h = lambda b: hashlib.sha512(b).hexdigest()
    return (
        f'''    aff4:mapPointHash       "{h(entry)}"^^aff4:SHA512 ;
    aff4:mapIdxHash         "{h(idx)}"^^aff4:SHA512 ;
    aff4:mapPathHash        "{h(mappath)}"^^aff4:SHA512 ;
    aff4:mapHash            "{h(entry + idx + mappath)}"^^aff4:SHA512 ;'''
    )


def write_tree(path: Path) -> None:
    """Several files in a nested tree.

    Exercises AFF4-L v1.0-ALPHA §1.1: every path is carried in properties, so
    a reader that recovers the tree from anything but those properties gets
    a flat bag of UUIDs.
    """
    files = {
        "aff4://11111111-1111-4111-8111-111111111111": (
            "notes.txt", "/case/notes.txt", b"top level\n"),
        "aff4://22222222-2222-4222-8222-222222222222": (
            "a.txt", "/case/sub/a.txt", b"nested one\n"),
        "aff4://33333333-3333-4333-8333-333333333333": (
            "b.txt", "/case/sub/deeper/b.txt", b"nested two\n"),
    }
    turtle = f"""
<{VOLUME}>
    a           aff4:ZipVolume ;
    aff4:stored "{path.name}" .
"""
    members = {}
    for arn, (name, full, content) in files.items():
        turtle += _file_subject(arn, name, full, content)
        members[arn] = content
    _write(path, turtle, members)


def write_uppercase_guid(path: Path) -> None:
    """A file whose ARN spells its GUID in upper case.

    AFF4-L v1.0-ALPHA §2 requires lower case. The container is otherwise
    well formed, so a reader must accept it and record the departure rather
    than refusing the evidence.
    """
    content = b"upper case guid\n"
    arn = "aff4://4A7B2C91-8D3E-4F05-9A6B-1C2D3E4F5061"
    turtle = f"""
<{VOLUME}>
    a           aff4:ZipVolume ;
    aff4:stored "{path.name}" .
""" + _file_subject(arn, "upper.txt", "/upper.txt", content)
    _write(path, turtle, {arn: content})


def write_escaped_member(path: Path) -> None:
    """A file whose bytes are stored under the old escaped member name.

    AFF4-L v1.0-ALPHA §1.2 stops escaping the scheme and identifier, and its
    §6.1 example shows the member stored literally. A v2.1 container using
    the v1.0a §5.2 spelling instead departs from that rule.
    """
    content = b"escaped member name\n"
    arn = "aff4://5b8c3d02-9e4f-4106-ab7c-2d3e4f506172"
    escaped = arn.replace(":", "%3A").replace("/", "%2F")
    turtle = f"""
<{VOLUME}>
    a           aff4:ZipVolume ;
    aff4:stored "{path.name}" .
""" + _file_subject(arn, "escaped.txt", "/escaped.txt", content)
    _write(path, turtle, {escaped: content})


def write_nameless(path: Path) -> None:
    """A FileImage carrying neither fileName nor originalPathName.

    AFF4-L v1.0-ALPHA §1.1 requires the path be carried in properties once
    the name is a GUID. Without them the file cannot be exported under any
    meaningful name, and the export must record the gap rather than inventing
    one.
    """
    content = b"no recorded name\n"
    arn = "aff4://6c9d4e13-af50-4217-bc8d-3e4f50617283"
    turtle = f"""
<{VOLUME}>
    a           aff4:ZipVolume ;
    aff4:stored "{path.name}" .

<{arn}>
    a           aff4:FileImage , aff4:Image , aff4:ZipSegment ;
    aff4:hash   "{hashlib.sha1(content).hexdigest()}"^^aff4:SHA1 ;
    aff4:size   "{len(content)}"^^xsd:long .
"""
    _write(path, turtle, {arn: content})


def _b64(data: bytes) -> str:
    """Base64, matching what the standard's raw name properties carry."""
    import base64 as _base64

    return _base64.b64encode(data).decode()


def _display(raw: bytes) -> str:
    """The AFF4-L v1.0-ALPHA section 5 display form of a name's bytes.

    Written from the standard's rules rather than from the aff4tools encoder,
    so a fixture cannot inherit a bug from the code it tests.
    """
    out = []
    for byte in raw:
        if byte <= 0x1F or byte == 0x25 or byte >= 0x7F:
            out.append(f"%{byte:02X}")
        else:
            out.append(chr(byte))
    return "".join(out)


def _named_file(arn: str, raw_name: bytes, raw_path: bytes, content: bytes,
                *, omit_raw=False, force_raw=False, bad_raw=None,
                lowercase=False, wrong_raw=None) -> str:
    """One FileImage subject with section 5 name properties.

    The keyword arguments each break one rule, so a fixture can be built that
    violates exactly one thing.
    """
    import hashlib

    encoded = any(b <= 0x1F or b == 0x7F for b in raw_name) or _is_bad_utf8(raw_name)
    name_display = _display(raw_name) if encoded else raw_name.decode()
    path_display = _display(raw_path) if encoded else raw_path.decode()
    if lowercase:
        # Only an escape carrying a hex letter can differ in case, so the
        # fixture that exercises this rule uses one.
        name_display = "".join(
            c.lower() if c in "ABCDEF" else c for c in name_display
        )

    lines = [
        f"<{arn}>",
        "    a                       aff4:FileImage , aff4:Image , aff4:ZipSegment ;",
        f'    aff4:hash               "{hashlib.sha1(content).hexdigest()}"^^aff4:SHA1 ;',
        f'    aff4:size               "{len(content)}"^^xsd:long ;',
        f'    aff4:originalPathName   "{path_display}" ;',
        f'    aff4:fileName           "{name_display}"',
    ]

    raw_value = None
    if bad_raw is not None:
        raw_value = bad_raw
    elif wrong_raw is not None:
        raw_value = _b64(wrong_raw)
    elif force_raw or (encoded and not omit_raw):
        raw_value = _b64(raw_name)

    if raw_value is not None:
        lines[-1] += " ;"
        lines.append(f'    aff4:fileNameRaw        "{raw_value}"^^xsd:base64Binary')
        # The path property is encoded too whenever the name is, so its own raw
        # form must be present or the container is missing half a pair. Written
        # from the path's real bytes, so only the deliberate defect above
        # differs between fixtures.
        if True:
            path_raw = _b64(raw_path if (force_raw or encoded) else raw_path)
            lines[-1] += " ;"
            lines.append(
                f'    aff4:originalPathNameRaw "{path_raw}"^^xsd:base64Binary'
            )
    lines[-1] += " ."
    return "\n" + "\n".join(lines) + "\n"


def _is_bad_utf8(raw: bytes) -> bool:
    try:
        raw.decode()
        return False
    except UnicodeDecodeError:
        return True


def _section5(path: Path, subject: str, members: dict = None) -> None:
    """A container holding one section 5 fixture subject.

    The subject declares aff4:ZipSegment, so the member it names is stored:
    a container that declares a storage form and holds nothing under it is
    reporting its own bytes missing, which is a separate fault from the naming
    rule each of these fixtures exists to isolate.
    """
    turtle = f"""
<{VOLUME}>
    a           aff4:ZipVolume ;
    aff4:stored "{path.name}" .
""" + subject
    _write(path, turtle, members or {})


def write_section5_fixtures(outdir: Path) -> int:
    """Every section 5 case, one container each."""
    F = "aff4://8d1f4a26-3b07-4c95-ae82-51d0c6f39b47"
    content = b"section five\n"
    cases = {
        # Conforming: a clean name, and an encoded name with a correct pair.
        "names-clean.aff4l": _named_file(
            F, b"report.txt", b"/case/report.txt", content),
        "names-encoded.aff4l": _named_file(
            F, b"ctrl\ttab.txt", b"/case/ctrl\ttab.txt", content),
        "names-invalid-utf8.aff4l": _named_file(
            F, b"bad\xffname.txt", b"/case/bad\xffname.txt", content),
        # Violations, one rule each.
        "names-redundant-raw.aff4l": _named_file(
            F, b"clean.txt", b"/case/clean.txt", content, force_raw=True),
        "names-missing-raw.aff4l": _named_file(
            F, b"ctrl\ttab.txt", b"/case/ctrl\ttab.txt", content, omit_raw=True),
        "names-malformed-raw.aff4l": _named_file(
            F, b"ctrl\ttab.txt", b"/case/ctrl\ttab.txt", content, bad_raw="not!base64"),
        "names-contradictory-raw.aff4l": _named_file(
            F, b"ctrl\ttab.txt", b"/case/ctrl\ttab.txt", content,
            wrong_raw=b"something\telse.txt"),
        # A carriage return escapes as %0D, whose letter can be lowercased;
        # a tab is %09 and has no letter to differ in.
        # A lowercase escape cannot appear in an otherwise conforming
        # container: with a raw form present it contradicts it, and without one
        # it also breaks rule 2. This fixture takes the second, so it reports
        # the spelling rule plus the missing raw form -- both genuine, and the
        # test asserts exactly that pair.
        "names-lowercase-escape.aff4l": _named_file(
            F, b"ctrl\rcr.txt", b"/case/ctrl\rcr.txt", content,
            lowercase=True, omit_raw=True),
    }
    for name, subject in cases.items():
        _section5(outdir / name, subject, {F: content})
    return len(cases)


def write_namespace_fixtures(outdir: Path) -> int:
    """Section 4.1: a term under the namespace its standard does not assign.

    Two cases, both well formed as RDF and both readable: what differs is
    whether a reader that declines to honor both namespaces would recognize
    the term.
    """
    import hashlib

    F = "aff4://9e2c5b71-4d38-4a06-bc19-70f3e8a24d5c"
    content = b"namespace\n"
    common = (
        "    a                       aff4:FileImage , aff4:Image , aff4:ZipSegment ;\n"
        f'    aff4:hash               "{hashlib.sha1(content).hexdigest()}"^^aff4:SHA1 ;\n'
        f'    aff4:size               "{len(content)}"^^xsd:long ;\n'
        '    aff4:fileName           "ns.txt" ;\n'
        '    aff4:originalPathName   "/ns.txt" ;\n'
    )

    cases = {
        # Correct: a v1.0-ALPHA term in the 2022 namespace.
        "namespace-correct.aff4l":
            f"\n<{F}>\n{common}"
            '    aff4l:pathSeparator     "/" .\n',
        # Wrong: a v1.0-ALPHA term under the base namespace.
        "namespace-base-for-new.aff4l":
            f"\n<{F}>\n{common}"
            '    aff4:pathSeparator      "/" .\n',
        # Wrong the other way: a base term under the 2022 namespace.
        "namespace-new-for-base.aff4l":
            f"\n<{F}>\n{common}"
            '    aff4l:fileMode          "420" .\n',
    }
    for name, subject in cases.items():
        turtle = f"""
<{VOLUME}>
    a           aff4:ZipVolume ;
    aff4:stored "{name}" .
""" + subject
        # The subject declares aff4:ZipSegment, so its member is stored. These
        # fixtures isolate a namespace fault and must carry no other.
        _write(outdir / name, turtle, {F: content})
    return len(cases)



# --- AFF4-L v1.0-ALPHA section 6 storage forms -------------------------------
#
# Section 6 defines four ways a logical stream's bytes may be stored, and
# requires a reader to support all of them. Each emitter below writes one form,
# so a reader can be tested against every one without this project's writer
# having produced any of them.

CHUNK_SIZE = 32 * 1024


def _volume_subject(path: Path) -> str:
    return f"""
<{VOLUME}>
    a           aff4:ZipVolume ;
    aff4:stored "{path.name}" .
"""


def _bevy(content: bytes) -> tuple:
    """One bevy holding one chunk, stored uncompressed.

    AFF4 Standard v1.0a section 3.2: a chunk whose stored length equals
    chunkSize is uncompressed, so the chunk is padded to chunkSize here and
    trimmed on read by aff4:size.
    """
    padded = content + b"\x00" * (CHUNK_SIZE - len(content))
    index = struct.pack("<QI", 0, CHUNK_SIZE)
    return padded, index


def write_in_metadata(path: Path) -> None:
    """A file whose bytes live in the turtle (AFF4-L v1.0-ALPHA section 6.2).

    Under the 1 Kb ceiling that clause sets. No aff4:hash: the same clause
    permits omitting digests for this form, relying on the metadata integrity
    hash, and a fixture that always carried them would never exercise that.
    """
    content = b"resident bytes, stored in the metadata"
    turtle = _volume_subject(path) + f"""
<{FILE_IMAGE}>
    a                       aff4:FileImage , aff4:Image ;
    aff4:size               "{len(content)}"^^xsd:long ;
    aff4:fileName           "resident.txt" ;
    aff4:originalPathName   "/case/resident.txt" ;
    aff4:stored             <{VOLUME}> ;
    aff4l:dataStream        "{_b64(content)}"^^xsd:base64Binary .
"""
    _write(path, turtle, {})


def write_zipsegment(path: Path) -> None:
    """A file stored as one ZIP segment (AFF4-L v1.0-ALPHA section 6.1)."""
    content = b"segment content, stored as a single ZIP member\n"
    turtle = _volume_subject(path) + f"""
<{FILE_IMAGE}>
    a                       aff4:FileImage , aff4:Image , aff4:ZipSegment ;
    aff4:hash               "{hashlib.sha512(content).hexdigest()}"^^aff4:SHA512 ;
    aff4:size               "{len(content)}"^^xsd:long ;
    aff4:fileName           "segment.txt" ;
    aff4:originalPathName   "/case/segment.txt" ;
    aff4:stored             <{VOLUME}> .
"""
    _write(path, turtle, {FILE_IMAGE: content})


def write_image_stream(path: Path) -> None:
    """A file stored as its own ImageStream (AFF4-L v1.0-ALPHA section 6.4)."""
    content = b"image stream content " * 8
    padded, index = _bevy(content)
    turtle = _volume_subject(path) + f"""
<{FILE_IMAGE}>
    a                       aff4:FileImage , aff4:Image , aff4:ImageStream ;
    aff4:hash               "{hashlib.sha512(content).hexdigest()}"^^aff4:SHA512 ;
    aff4:size               "{len(content)}"^^xsd:long ;
    aff4:chunkSize          "{CHUNK_SIZE}"^^xsd:int ;
    aff4:chunksInSegment    "1"^^xsd:int ;
    aff4:fileName           "stream.txt" ;
    aff4:originalPathName   "/case/stream.txt" ;
    aff4:stored             <{VOLUME}> .
"""
    _write(path, turtle, {
        f"{FILE_IMAGE}/00000000": padded,
        f"{FILE_IMAGE}/00000000.index": index,
    })


def write_map(path: Path) -> None:
    """A FileImage carrying the Map type (AFF4-L v1.0-ALPHA section 6.3).

    The first of that clause's two forms: the aff4:Map type is added to the
    FileImage instance, so one subject is both Image and Map. The second form,
    where aff4l:dataStream points at a separate Map subject, is written by
    write_map_indirect.
    """
    content = b"mapped content, addressed through a map entry"
    padded, index = _bevy(content)
    stream = "aff4://0947bfd0-1265-42d3-95b6-8d7bed108e9b"
    # AFF4 Standard v1.0a section 4: mappedOffset, length, targetOffset, target id.
    entry = struct.pack("<QQQI", 0, len(content), 0, 0)
    turtle = _volume_subject(path) + f"""
<{FILE_IMAGE}>
    a                       aff4:FileImage , aff4:Image , aff4:Map ;
    aff4:dependentStream    <{stream}> ;
{_map_digests(entry, (stream + chr(10)).encode())}
    aff4:hash               "{hashlib.sha512(content).hexdigest()}"^^aff4:SHA512 ;
    aff4:size               "{len(content)}"^^xsd:long ;
    aff4:fileName           "mapped.txt" ;
    aff4:originalPathName   "/case/mapped.txt" ;
    aff4:stored             <{VOLUME}> .

<{stream}>
    a                       aff4:ImageStream ;
    aff4:size               "{len(content)}"^^xsd:long ;
    aff4:chunkSize          "{CHUNK_SIZE}"^^xsd:int ;
    aff4:chunksInSegment    "1"^^xsd:int ;
    aff4:stored             <{VOLUME}> .
"""
    _write(path, turtle, {
        f"{FILE_IMAGE}/map": entry,
        f"{FILE_IMAGE}/idx": (stream + "\n").encode(),
        f"{stream}/00000000": padded,
        f"{stream}/00000000.index": index,
    })


def write_map_indirect(path: Path) -> None:
    """The second AFF4-L v1.0-ALPHA section 6.3 form: a separate Map subject.

    The FileImage reaches its Map through aff4l:dataStream. This project's
    writer never emits this shape, and a reader must still handle it.
    """
    content = b"indirectly mapped content"
    padded, index = _bevy(content)
    themap = "aff4://31aa452b-bddf-4257-a998-5bb75a80f9b1"
    stream = "aff4://0947bfd0-1265-42d3-95b6-8d7bed108e9b"
    entry = struct.pack("<QQQI", 0, len(content), 0, 0)
    turtle = _volume_subject(path) + f"""
<{FILE_IMAGE}>
    a                       aff4:FileImage , aff4:Image ;
    aff4:size               "{len(content)}"^^xsd:long ;
    aff4:fileName           "indirect.txt" ;
    aff4:originalPathName   "/case/indirect.txt" ;
    aff4:stored             <{VOLUME}> ;
    aff4l:dataStream        <{themap}> .

<{themap}>
    a                       aff4:Map ;
    aff4:dependentStream    <{stream}> ;
{_map_digests(entry, (stream + chr(10)).encode())}
    aff4:hash               "{hashlib.sha512(content).hexdigest()}"^^aff4:SHA512 ;
    aff4:size               "{len(content)}"^^xsd:long ;
    aff4:stored             <{VOLUME}> .

<{stream}>
    a                       aff4:ImageStream ;
    aff4:size               "{len(content)}"^^xsd:long ;
    aff4:chunkSize          "{CHUNK_SIZE}"^^xsd:int ;
    aff4:chunksInSegment    "1"^^xsd:int ;
    aff4:stored             <{VOLUME}> .
"""
    _write(path, turtle, {
        f"{themap}/map": entry,
        f"{themap}/idx": (stream + "\n").encode(),
        f"{stream}/00000000": padded,
        f"{stream}/00000000.index": index,
    })


def write_substreams(path: Path) -> None:
    """A file carrying an extended attribute and an alternate data stream.

    AFF4-L v1.0-ALPHA section 4.2 defines FileExtendedAttribute and
    FileSubStream; section 4.3 gives the properties that reach them. The ADS is
    present because a reader must handle the shape even though acquisition on a
    supported platform never produces one.
    """
    content = b"parent file content\n"
    attr = b"attribute value"
    ads = b"alternate stream value"
    xattr_arn = "aff4://bfcecaf5-7272-4476-8f57-e72017271b1c"
    ads_arn = "aff4://c4e11a37-9d52-4f80-b6a3-1e7c0d8f2b95"
    turtle = _volume_subject(path) + f"""
<{FILE_IMAGE}>
    a                          aff4:FileImage , aff4:Image , aff4:ZipSegment ;
    aff4:hash                  "{hashlib.sha512(content).hexdigest()}"^^aff4:SHA512 ;
    aff4:size                  "{len(content)}"^^xsd:long ;
    aff4:fileName              "parent.txt" ;
    aff4:originalPathName      "/case/parent.txt" ;
    aff4:stored                <{VOLUME}> ;
    aff4l:extendedAttribute    <{xattr_arn}> ;
    aff4l:alternateDataStream  <{ads_arn}> .

<{xattr_arn}>
    a                       aff4:FileExtendedAttribute ;
    aff4:size               "{len(attr)}"^^xsd:long ;
    aff4:name               "user.comment" ;
    aff4:target             <{FILE_IMAGE}> ;
    aff4l:dataStream        "{_b64(attr)}"^^xsd:base64Binary .

<{ads_arn}>
    a                       aff4:FileSubStream , aff4:Image ;
    aff4:size               "{len(ads)}"^^xsd:long ;
    aff4:name               "hidden" ;
    aff4:target             <{FILE_IMAGE}> ;
    aff4l:dataStream        "{_b64(ads)}"^^xsd:base64Binary .
"""
    _write(path, turtle, {FILE_IMAGE: content})


# --- Negative fixtures for strict dispatch ----------------------------------
#
# AFF4-L v1.0-ALPHA section 6 makes the rdf:type list the dispatch key. Each of
# these states where its bytes are and is wrong about it, which must be refused
# rather than worked around: a reader that searched could match another
# stream's bytes and report success over the wrong data.

def write_bad_missing_member(path: Path) -> None:
    """Typed ZipSegment, with no such member in the container."""
    turtle = _volume_subject(path) + f"""
<{FILE_IMAGE}>
    a                       aff4:FileImage , aff4:Image , aff4:ZipSegment ;
    aff4:size               "19"^^xsd:long ;
    aff4:fileName           "absent.txt" ;
    aff4:originalPathName   "/case/absent.txt" ;
    aff4:stored             <{VOLUME}> .
"""
    _write(path, turtle, {})


def write_bad_undecodable_base64(path: Path) -> None:
    """An aff4l:dataStream literal whose content is not valid base64."""
    turtle = _volume_subject(path) + f"""
<{FILE_IMAGE}>
    a                       aff4:FileImage , aff4:Image ;
    aff4:size               "10"^^xsd:long ;
    aff4:fileName           "bad.txt" ;
    aff4:originalPathName   "/case/bad.txt" ;
    aff4:stored             <{VOLUME}> ;
    aff4l:dataStream        "!!!not base64!!!"^^xsd:base64Binary .
"""
    _write(path, turtle, {})


def write_bad_two_storage_types(path: Path) -> None:
    """Both ZipSegment and ImageStream: the bytes are named in two places."""
    content = b"hello"
    turtle = _volume_subject(path) + f"""
<{FILE_IMAGE}>
    a                       aff4:FileImage , aff4:Image ,
                            aff4:ZipSegment , aff4:ImageStream ;
    aff4:size               "{len(content)}"^^xsd:long ;
    aff4:fileName           "two.txt" ;
    aff4:originalPathName   "/case/two.txt" ;
    aff4:stored             <{VOLUME}> .
"""
    _write(path, turtle, {FILE_IMAGE: content})



def write_in_metadata_hashed(path: Path) -> None:
    """An in-metadata stream that does record a digest.

    AFF4-L v1.0-ALPHA section 6.2 permits omitting digests for this form;
    write_in_metadata exercises that. This one records a digest so the
    comparison path is exercised too.
    """
    content = b"resident bytes with a recorded digest"
    turtle = _volume_subject(path) + f"""
<{FILE_IMAGE}>
    a                       aff4:FileImage , aff4:Image ;
    aff4:hash               "{hashlib.sha512(content).hexdigest()}"^^aff4:SHA512 ;
    aff4:size               "{len(content)}"^^xsd:long ;
    aff4:fileName           "resident-hashed.txt" ;
    aff4:originalPathName   "/case/resident-hashed.txt" ;
    aff4:stored             <{VOLUME}> ;
    aff4l:dataStream        "{_b64(content)}"^^xsd:base64Binary .
"""
    _write(path, turtle, {})


def write_in_metadata_wrong_digest(path: Path) -> None:
    """An in-metadata stream whose recorded digest does not match its bytes.

    The bytes decode and the form is well formed, so this is not malformed: it
    is an integrity failure, and verify must report a mismatch rather than
    passing it over.
    """
    content = b"resident bytes that do not match"
    wrong = hashlib.sha512(b"different content entirely").hexdigest()
    turtle = _volume_subject(path) + f"""
<{FILE_IMAGE}>
    a                       aff4:FileImage , aff4:Image ;
    aff4:hash               "{wrong}"^^aff4:SHA512 ;
    aff4:size               "{len(content)}"^^xsd:long ;
    aff4:fileName           "resident-bad.txt" ;
    aff4:originalPathName   "/case/resident-bad.txt" ;
    aff4:stored             <{VOLUME}> ;
    aff4l:dataStream        "{_b64(content)}"^^xsd:base64Binary .
"""
    _write(path, turtle, {})



def write_oversized_resident(path: Path) -> None:
    """An in-metadata stream above the AFF4-L v1.0-ALPHA section 6.2 cap.

    That clause forbids the form above 1 Kb. The bytes are present and
    unambiguously this stream's, so a reader must read it and report the
    departure rather than refusing the container.
    """
    content = bytes((i % 251) for i in range(4096))
    turtle = _volume_subject(path) + f"""
<{FILE_IMAGE}>
    a                       aff4:FileImage , aff4:Image ;
    aff4:hash               "{hashlib.sha512(content).hexdigest()}"^^aff4:SHA512 ;
    aff4:size               "{len(content)}"^^xsd:long ;
    aff4:fileName           "oversized.bin" ;
    aff4:originalPathName   "/case/oversized.bin" ;
    aff4:stored             <{VOLUME}> ;
    aff4l:dataStream        "{_b64(content)}"^^xsd:base64Binary .
"""
    _write(path, turtle, {})



def write_unreadable_file_record(path: Path) -> None:
    """A file recorded without content, because it could not be read.

    An acquisition that hits a permission error still records that the file
    existed, with its name, times, and mode, and stores no bytes for it. There
    is no storage form to declare, so a container holding one is not
    contradicting itself: the omission is a completeness finding the
    acquisition reports in its own SKIPPED list.

    The shape is no aff4:size and no aff4:hash. Real acquisitions produce it:
    a scan of /Library on a stock macOS system recorded 23 such files.
    """
    turtle = _volume_subject(path) + f"""
<{FILE_IMAGE}>
    a                       aff4:FileImage , aff4:Image ;
    aff4:fileName           "unreadable.plist" ;
    aff4:originalPathName   "/case/unreadable.plist" ;
    aff4:fileMode           "33184"^^xsd:long ;
    aff4:stored             <{VOLUME}> .
"""
    _write(path, turtle, {})


def write_storage_fixtures(outdir: Path) -> int:
    """Every AFF4-L v1.0-ALPHA section 6 storage form, and the negatives."""
    write_in_metadata(outdir / "storage-in-metadata.aff4l")
    write_in_metadata_hashed(outdir / "storage-in-metadata-hashed.aff4l")
    write_in_metadata_wrong_digest(outdir / "storage-in-metadata-wrong.aff4l")
    write_zipsegment(outdir / "storage-zipsegment.aff4l")
    write_image_stream(outdir / "storage-imagestream.aff4l")
    write_map(outdir / "storage-map.aff4l")
    write_map_indirect(outdir / "storage-map-indirect.aff4l")
    write_substreams(outdir / "storage-substreams.aff4l")
    write_oversized_resident(outdir / "storage-oversized-resident.aff4l")
    write_unreadable_file_record(outdir / "storage-unreadable-record.aff4l")
    write_bad_missing_member(outdir / "bad-missing-member.aff4l")
    write_bad_undecodable_base64(outdir / "bad-undecodable-base64.aff4l")
    write_bad_two_storage_types(outdir / "bad-two-storage-types.aff4l")
    return 13


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("outdir", type=Path)
    args = parser.parse_args()
    args.outdir.mkdir(parents=True, exist_ok=True)

    write_minimal(args.outdir / "minimal.aff4l")
    write_conformant(args.outdir / "conformant.aff4l")
    write_tree(args.outdir / "tree.aff4l")
    write_uppercase_guid(args.outdir / "uppercase-guid.aff4l")
    write_escaped_member(args.outdir / "escaped-member.aff4l")
    write_nameless(args.outdir / "nameless.aff4l")
    extra = write_section5_fixtures(args.outdir)
    extra += write_namespace_fixtures(args.outdir)
    extra += write_storage_fixtures(args.outdir)
    print(f"wrote {6 + extra} v2.1 containers to {args.outdir}")


if __name__ == "__main__":
    main()
