#!/usr/bin/env python3
"""Create minimal AFF4-L Standard v1.0-ALPHA (v2.1) containers.

Purpose: Create small test .aff4l v2.1 containers without relying on
the aff4tools writer. Adjust this script as the 2026 spec evolves.

Written independently of the aff4tools writer, so a reader bug and a writer bug
cannot cancel out. Nothing here is copied from the specification: the UUIDs,
sizes, and content are generated by this script.

These are NOT accepted, canonical reference images and must not be presented as such.
They are test inputs for an AFF4-L reader that has no other v2.1 containers to read.
"""

import argparse
import hashlib
import zipfile
from pathlib import Path

VOLUME = "aff4://3f2b91c4-5d7e-4a18-9c60-2e8b7f14a3d9"
FILE_IMAGE = "aff4://7c41e082-b3a9-4f56-8d21-6a0f9e5c7b34"

TURTLE_PREFIXES = """\
@prefix aff4:  <http://aff4.org/Schema#> .
@prefix aff4l: <http://aff4.org/Schema/2022/#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
"""


def write_minimal(path: Path) -> None:
    """A v2.1 container declaring only its volume."""
    turtle = TURTLE_PREFIXES + f"""
<{VOLUME}>
    a           aff4:ZipVolume ;
    aff4:stored "{path.name}" .
"""
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        # container.description first, per AFF4 Standard v1.0a §5.4.
        z.writestr("container.description", VOLUME)
        z.writestr("version.txt", "major=2\nminor=1\ntool=aff4tools-test 0.1\n")
        z.writestr("information.turtle", turtle)
        z.comment = VOLUME.encode()


def write_conformant(path: Path) -> None:
    """A v2.1 container with one file stored as a ZIP segment."""
    content = b"This is test content.\n"
    sha1 = hashlib.sha1(content).hexdigest()
    md5 = hashlib.md5(content).hexdigest()

    turtle = TURTLE_PREFIXES + f"""
<{VOLUME}>
    a           aff4:ZipVolume ;
    aff4:stored "{path.name}" .

<{FILE_IMAGE}>
    a                       aff4:FileImage , aff4:Image , aff4:ZipSegment ;
    aff4:hash               "{sha1}"^^aff4:SHA1 , "{md5}"^^aff4:MD5 ;
    aff4:size               "{len(content)}"^^xsd:long ;
    aff4l:fileName          "test.txt" ;
    aff4l:originalPathName  "/test.txt" .
"""
    turtle_bytes = turtle.encode()
    hashes = TURTLE_PREFIXES + f"""
<{VOLUME}/information.turtle>
    aff4:hash "{hashlib.sha256(turtle_bytes).hexdigest()}"^^aff4:SHA256 .
"""
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("container.description", VOLUME)
        z.writestr("version.txt", "major=2\nminor=1\ntool=aff4tools-test 0.1\n")
        # The stream's content lives under its own ARN as the member name,
        # per AFF4-L v1.0-ALPHA §6.1.
        z.writestr(FILE_IMAGE, content)
        z.writestr("information.turtle", turtle_bytes)
        z.writestr("information.turtle.hashes", hashes)
        z.comment = VOLUME.encode()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("outdir", type=Path)
    args = parser.parse_args()
    args.outdir.mkdir(parents=True, exist_ok=True)

    write_minimal(args.outdir / "minimal.aff4l")
    write_conformant(args.outdir / "conformant.aff4l")
    print(f"wrote 2 v2.1 containers to {args.outdir}")


if __name__ == "__main__":
    main()
